### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by seeeeew** [Kinkelin/WordleCompetition#1]
1. You should add a license to the repository. Otherwise people aren't really allowed to download, use, and modify your code. See https://choosealicense.com/ and https://help.github.com/articles/adding-a-license-to-a-repository/ for more info.

2. What licenses apply to the different word lists in this repository? While the words themselves obviously aren't protected, the specific _selections_ of these words can be creative works protected under copyright law depending on your jurisdiction and standpoint and on how they were created. You should probably check under which license you can use and distribute each word list.

**Comment by Kinkelin** [comment]
Thanks for pointing that out! Lists without a clear license have been removed now and a license was added to the repository itself.
